version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aitosql-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlServer@Pass123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./docker/sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SqlServer@Pass123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Initialize SQL Server database
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./docker/sqlserver/init.sql:/init.sql
    command: >
      sh -c "
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P SqlServer@Pass123! -Q 'CREATE DATABASE testdb;' &&
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P SqlServer@Pass123! -d testdb -i /init.sql
      "

  # MCP Server
  mcp-server:
    build: .
    container_name: aitosql-mcp-server
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    environment:
      # Database Connection
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=testdb;encrypt=false;trustServerCertificate=true
      DB_USERNAME: readonly_user
      DB_PASSWORD: ReadOnly@Pass123!
      DB_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
      DB_TYPE: SQLServer
      
      # Server Configuration
      SERVER_PORT: 8080
      CACHE_ENABLED: true
      
      # Spring Boot Configuration
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_MAGACHO: DEBUG
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  sqlserver_data:
    driver: local

# ============================================================================
# USAGE
# ============================================================================
#
# Start services:
#   docker-compose -f docker-compose-sqlserver.yml up -d
#
# View logs:
#   docker-compose -f docker-compose-sqlserver.yml logs -f mcp-server
#
# Stop services:
#   docker-compose -f docker-compose-sqlserver.yml down
#
# Stop and remove volumes:
#   docker-compose -f docker-compose-sqlserver.yml down -v
#
# Test MCP Server:
#   curl http://localhost:8080/mcp/tools/list
#
# Note: SQL Server requires at least 2GB of RAM to run
# ============================================================================
